# The use of implicit sources has been deprecated.
source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

# Use frameworks instead of static libraries for Pods.
use_frameworks!

platform :ios, '9.0'

def all_pods
    #Networking
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'

    #Tools
    pod 'SkyFloatingLabelTextField'
    pod 'TPKeyboardAvoiding'
    pod 'TSMessages'
    pod 'SVProgressHUD'

    #gif
    pod 'SDWebImage', '~>3.8'
end

target "MyGif" do
    all_pods
end
